# render.yaml — raíz del monorepo cb-tomelloso
services:
  # ─── BACKEND NestJS ───────────────────────────────────────────────
  - type: web
    name: cb-tomelloso-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/main
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: api/v1
      - key: DB_HOST
        value: mysql-9465549-robercalero2004-69ea.i.aivencloud.com
      - key: DB_PORT
        value: "16883"
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_NAME
        value: cbtomelloso
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: https://cb-tomelloso-web.onrender.com,http://localhost:4200
      - key: THROTTLE_TTL
        value: "60000"
      - key: THROTTLE_LIMIT
        value: "60"
      - key: INSTAGRAM_ACCESS_TOKEN
        sync: false
      - key: INSTAGRAM_USER_ID
        sync: false

  # ─── FRONTEND Angular ─────────────────────────────────────────────
  - type: static
    name: cb-tomelloso-web
    runtime: static
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/cb-tomelloso-web/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600, s-maxage=3600

